pattern_cols: 11      # 棋盘格每行的内角点数（格子数-1）
pattern_rows: 8      # 棋盘格每列的内角点数（格子数-1）
square_size_mm: 30   # 棋盘格方块大小（毫米）

enemy_color: "auto"
# enemy_color: "blue"
# enemy_color: "red"


#####-----神经网络参数-----#####
yolo_name: yolov8
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

# #####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
# min_confidence: 0.8

number_classifier:
  model_path: "../assets/rv_model/mlp.onnx"   # 模型路径 (确保文件存在)
  label_path: "../assets/rv_model/label.txt"  # 标签文件路径
  threshold: 0.5                 # 数字分类阈值
  ignore_classes: ["negative"]   # 忽略的类别


#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 11
outpost_max_temp_lost_count: 75

#####-----aimer参数-----##### 6mm
# yaw_offset: 0.5 # degree -2.5
# pitch_offset: 3.2 # degree 2
# comming_angle: 60 # degree
# leaving_angle: 20 # degree
# decision_speed: 8 # rad/s
# high_speed_delay_time: 0.12 # s
# low_speed_delay_time: 0.093 # s

#####-----aimer参数-----##### 12mm
yaw_offset: -0.5 # degree 
pitch_offset: 0.4 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 8 # rad/

high_speed_delay_time: 0.018 # s   远 0.25
low_speed_delay_time: 0.017 # s    远 0.25
far_pitch_offset: 1.2

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#12mm camera
# camera_name: "hikrobot"
# camera_sn: "DA7188471"
# exposure_us: 6000
# gain: 0.7
# gamma: 0.5  
# vid_pid: "2ba2:4d55"
# flip: true
# mirror: true

#6mm camera
# camera_name: "hikrobot"
# camera_sn: "DA7188471"
# exposure_us: 9000
# gain: 0.5
# vid_pid: "2bdf:0001"
# flip: true
# mirror: true

camera_name: "daheng"
camera_sn: "FDN24040487"
exposure_us: 4000
gain: 0.4
gamma: 0.6
img_gamma: 1
vid_pid: "2ba2:4d55"
flip: true
mirror: true

# -1  0  0
#  0 -1  0
#  0  0  1
# R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]
R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]

# # 6mm camera
# # 重投影误差: 0.0787px
# camera_matrix: [1809.564717217451, 0, 706.3327817682249, 0, 1805.15500074533, 538.4969433458281, 0, 0, 1]
# distort_coeffs: [-0.07041439840690113, 0.151412749802884, 0.0007210441135535533, -0.0006368697407199156, -0.03172837319091361]
# # 相机同理想情况的偏角: yaw-1.74 pitch-1.63 roll1.35 degree
# # 标定板到世界坐标系原点的水平距离: 2.17 m
# # 标定板同竖直摆放时的偏角: yaw-0.69 pitch16.89 roll-2.66 degree
# R_camera2gimbal: [0.029716925347032186, -0.02905823526614317, 0.9991358883110625, -0.9992825867505816, 0.02261477470051248, 0.030379002325802554, -0.023477993206084943, -0.9993218655310523, -0.028365346931643467]
# t_camera2gimbal: [0.09950350840289986, -0.0178102433697989, 0.042332935712018425]
# # _camera2gimbal第一位调yaw
# # _camera2gimbal第二位调yaw
# # _camera2gimbal第三位调pitch

# #12mm camera
# 相机同理想情况的偏角: yaw-1.01 pitch0.40 roll-3.17 degree
# 标定板到世界坐标系原点的水平距离: 3.99 m
# 标定板同竖直摆放时的偏角: yaw18.59 pitch10.91 roll179.05 degree
R_camera2gimbal: [0.01724177990211943, 0.008031166851665581, 0.9998190943289729, -0.9983196678891441, -0.05519050378990992, 0.017659246788155888, 0.05532234387221791, -0.9984435430460833, 0.007066089305084381]
t_camera2gimbal: [-0.06053188184293589, 0.04306961926275315, 0.07400899334239491]
# 重投影误差: 0.1039px
camera_matrix: [4733.43401413086, 0, 599.7636786594903, 0, 4741.85173415842, 478.8499763209543, 0, 0, 1]
distort_coeffs: [0.021580388912033843, -1.367908470971454, -0.0014335525678331896, -0.0030262393654059178, 31.166315287522888]
gimbal_y1: 1
gimbal_p2: 2
gimbal_r3: 3
#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM1"


#####-----planner-----#####
target_dist_error: 0.0
target_h_error: 0.4
fire_thresh: 0.003 # 
small_armor_tolerance: 0.03
big_armor_tolerance: 0.22
tower_and_base_armor_tolerance_: 0.10  # 26赛季前哨站和基地装甲板检测宽度
gimbal_control_delay: 0.02 
tower_pitch_prediction_time: 0.3

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6,0]
R_pitch: [1]



# auto q = gimbal.q(t - 1ms);

# float yaw = ypr[0];
# float pitch = ypr[1];
# float roll = ypr[2];

# Eigen::Quaterniond q = 
#     Eigen::AngleAxisd(yaw, Eigen::Vector3d::UnitZ()) *   // 绕Z轴旋转yaw
#     Eigen::AngleAxisd(pitch, Eigen::Vector3d::UnitY()) * // 绕Y轴旋转pitch
#     Eigen::AngleAxisd(-roll, Eigen::Vector3d::UnitX());   // 绕X轴旋转roll
